### ISSUE TITLE
[기능 추가] Memo CRUD

### ISSUE THREAD

**Issue by hyun987** [DibiDibiDeep/Final-back#8]

**Comment by okchang95** [comment]
메모 생성 요청 api, 저장 db 등
read시 단일조회인지 리스트인지 조건이 들어가는지에 따라 리뷰가 다름
각각 리소스가 다르게 들어가기에 분리 필요

메모를 조회할 때 어떻게 조회하는지 
- 조회하는 기능 추가
- 메모 read가 고려가 안됨 -> 나눠야함

메모 조회에 대한 검토
메모가 조회되서 나오는 결과도 결정이 안됨(res에 대한 모델안에 뭐가들어갈지) -> 쪼개지는게 맞음
